# To create 3D, 2D, and 1D arrays 
Creating 3D, 2D, and 1D arrays in Python typically involves using libraries like NumPy, which provides convenient and efficient array operations. Here are the steps for creating arrays of different dimensions using NumPy:

# Make sure to install NumPy if you haven't already:

NumPy is a powerful library for numerical operations in Python, and it provides a versatile and efficient array object for working with multi-dimensional data.

In [ ]:
pip install numpy

# 1. Creating a 1D Array:

In [1]:
import numpy as np

# Using a list to create a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])

print("1D Array:")
print(arr_1d)


1D Array:
[1 2 3 4 5]


# 2. Creating a 2D Array:

In [2]:
import numpy as np

# Using a list of lists to create a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("2D Array:")
print(arr_2d)


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 3. Creating a 3D Array:

In [3]:
import numpy as np

# Using nested lists to create a 3D NumPy array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("3D Array:")
print(arr_3d)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
